apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: uptime-kuma-forward-auth
  namespace: uptime-kuma
spec:
  forwardAuth:
    address: http://oauth2-proxy.uptime-kuma.svc.cluster.local:80
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
