service:
  type: ClusterIP

persistence:
  enabled: true
  existingClaim: portainer-pvc

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: my-app-my-app-redirect-https@kubernetescrd
  tls:
    - hosts:
        - portainer.saurabhmate.cloud
      secretName: portainer-tls
  hosts:
    - host: portainer.saurabhmate.cloud
      paths:
        - path: /
          pathType: Prefix
